### PR TITLE
My idea

### PR DESCRIPTION
**Pull request by maraisr**

### CODE REVIEW

**Comment by lanzafame** [comment]
So I am only starting out in web dev, so pardon my ignorance but what is the purpose/goal of mangle the selectors?

**Comment by maraisr** [comment]
Performance. See with css, the longer the nest the slower it takes to render. So i want to eventually evolve this into actually assessing the dom, and create move, and alter selectors to get those selectors down to as low as possible nesting.

See Google, Facebook, and all the large guys do it. Because they have millions of traffic a day and thus billions of transit a day so the tiniest change in speed or servability of assets might just save them terabytes of transit. 

Now im not saying coz Google does it, we must do it. Obviously their scope is a lot different than the average website. But I see it as more of a challenge to get selectors mangled effectively. And frankly there is nothing out there in the open source world or paid source world that does this, now just imagine if we could actually pull this off in a npm sort of scenario and actually help improve the web as we know it.

Ultimately who wouldn't want to try and protect IP in terms of how things are done on major websites simply because we as human cannot make sense of anything selector base.

I mean come on, Google Closure Compiler did wonders to JS, why not have something similar for styles!

**Comment by lanzafame** [comment]
Add that last comment to the README, it explains your goals and why you want to accomplish them a lot better :). Great idea by the way

**Comment by maraisr** [comment]
Done. Approve the pull yeah?

**Pull request merged**
